modules/aws: modules/aws/**
modules/bash: modules/bash/**
modules/chamber: modules/chamber/**
modules/codefresh: modules/codefresh/**
modules/completion: modules/completion/**
modules/compose: modules/compose/**
modules/docker: modules/docker/**
modules/docs: modules/docs/**
modules/geodesic: modules/geodesic/**
modules/git: modules/git/**
modules/github: modules/github/**
modules/gitleaks: modules/gitleaks/**
modules/go: modules/go/**
modules/helm: modules/helm/**
modules/helmfile: modules/helmfile/**
modules/jenkins: modules/jenkins/**
modules/make: modules/make/**
modules/packages: modules/packages/**
modules/readme: modules/readme/**
modules/semver: modules/semver/**
modules/slack: modules/slack/**
modules/template: modules/template/**
modules/terraform: modules/terraform/**
modules/travis: modules/travis/**
