sudo: required
language: go
go:
  - 1.7.x
addons:
  apt:
    packages:
    - git
    - make
    - curl

install:
- make all

script:
  - "make bash:lint"
  - "make make:lint"
  - "make terraform:install"
