language: go
go:
  - 1.9.x

addons:
  apt:
    packages:
    - git
    - make
    - curl

services:
- docker

install:
- make docker/login
- make go/deps-build
- make go/deps-dev
- make readme/deps

script:
- make bash/lint
- make make/lint
- make terraform/install
- make docker/build

after_success:
- make travis/docker-tag-and-push
