name: main-branch
on:
  push:
    branches: [ main ]

permissions:
  contents: write
  id-token: write

jobs:
  terraform-module:
    uses: cloudposse/github-actions-workflows-terraform-module/.github/workflows/main-branch.yml@main
    secrets:
      github_access_token: ${{ secrets.REPO_ACCESS_TOKEN }}
