.PHONY: go\:lint
## Lint code
go\:lint: $(GO) go\:vet
	find . ! -path "*/vendor/*" ! -path "*/.glide/*" -type f -name '*.go' | xargs -n 1 golint

.PHONY: go\:vet
## Vet code
go\:vet: $(GO)
	find . ! -path "*/vendor/*" ! -path "*/.glide/*" -type f -name '*.go' | xargs -n 1 $(GO) vet -v

.PHONY: go\:fmt
## Format code according to Golang convention
go\:fmt: $(GO)
	find . ! -path "*/vendor/*" ! -path "*/.glide/*" -type f -name '*.go' | xargs -n 1 gofmt -w -l -s
