## Lint code
go/lint: $(GO) go/vet
	$(call assert-set,GO)
	find . ! -path "*/vendor/*" ! -path "*/.glide/*" -type f -name '*.go' | xargs -n 1 golint

## Vet code
go/vet: $(GO)
	$(call assert-set,GO)
	find . ! -path "*/vendor/*" ! -path "*/.glide/*" -type f -name '*.go' | xargs $(GO) tool vet -v

## Format code according to Golang convention
go/fmt: $(GO)
	$(call assert-set,GO)
	find . ! -path "*/vendor/*" ! -path "*/.glide/*" -type f -name '*.go' | xargs -n 1 gofmt -w -l -s
