## Use DOCKER_IMAGE_NAME envvar to specify docker image with tags
## User ARGS to pass arguments
DOCKER_BUILD_FLAGS ?= --no-cache

.PHONY: docker\:build
## Build docker image
docker\:build: $(DOCKER)
	$(call assert-set,DOCKER)
	$(call assert-set,DOCKER_IMAGE_NAME)
	@BUILD_ARGS=`for arg in $$ARGS; do \
		printf -- '--build-arg %s=%s ' "$$arg" "$${!arg}"; \
	done`; \
	$(DOCKER) build $(DOCKER_BUILD_FLAGS) $$BUILD_ARGS -t $(DOCKER_IMAGE_NAME) .
