.PHONY: travis\:docker-tag-and-push
## Tag & Push according Travis environment variables
travis\:docker-tag-and-push:
	$(call assert-set,DOCKER_IMAGE_NAME)
	$(BUILD_HARNESS_PATH)/bin/travis_docker_tag_and_push.sh
