blank_issues_enabled: false
contact_links:
  - name: Community Slack Team
    url: https://cloudposse.com/slack/
    about: Please ask and answer questions here.
  - name: Office Hours
    url: https://cloudposse.com/office-hours/
    about: Join us every Wednesday for FREE Office Hours (lunch & learn).
  - name: Paid Support
    url: https://cloudposse.com/accelerate/
    about: Hire Cloud Posse to help you.