## Show
timestamp/show:
	@echo "Unix timestamp: ${BH_TIMESTAMP}"
	@echo "Human friendly timestamp: " $(shell date -d @${BH_TIMESTAMP})

## Export timestamp vars
timestamp/export:
	@echo "BH_TIMESTAMP=$(BH_TIMESTAMP)"
