sudo: required
addons:
  apt:
    packages:
    - git
    - make
    - curl
env:
  - DOCKER_IMAGE_NAME=neildmorris/#####################
services:
- docker
install:
- make init
- make travis:docker-login

script:
- make docker:build

after_success:
- make travis:docker-tag-and-push
