name: auto-greet

on: [pull_request, issues]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: |-
          Thank you for reporting the issue! If you haven't already [joined our slack community](https://slack.sweetops.com), then we invite you to do so.

          This is a great place to get help and ask questions from our AMAZING community.  

          [![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)
        pr-message: |-
          Thank you for submitting this PR! If you haven't already [joined our slack community](https://slack.sweetops.com), then we invite you to do so.

          We receive an overwhelming number of contributions. By joining our slack, we'll be able to review your PR faster.

          [![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)
