name: docker
on:
  push:
    branches:
      - master
  pull_request: 
    types: [opened, synchronize, reopened]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: docker/build-and-push
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ github.repository }}
          registry: registry-1.docker.io
          tag_with_ref: true
          tag_with_sha: true
